//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaStream.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeaStream.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional bytes must not be negative.
        /// </summary>
        internal static string AdditionalBytesMustNotBeNegative {
            get {
                return ResourceManager.GetString("AdditionalBytesMustNotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer size must be positive!.
        /// </summary>
        internal static string BufferSizeMustBePositive {
            get {
                return ResourceManager.GetString("BufferSizeMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot seek before beginning of file!.
        /// </summary>
        internal static string CannotSeekBeforeBeginningOfFile {
            get {
                return ResourceManager.GetString("CannotSeekBeforeBeginningOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count negative.
        /// </summary>
        internal static string CountNegative {
            get {
                return ResourceManager.GetString("CountNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid seek offset.
        /// </summary>
        internal static string InvalidSeekOffset {
            get {
                return ResourceManager.GetString("InvalidSeekOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SeekOrigin {0}.
        /// </summary>
        internal static string InvalidSeekOriginOrigin {
            get {
                return ResourceManager.GetString("InvalidSeekOriginOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length cannot be negative!.
        /// </summary>
        internal static string LengthCannotBeNegative {
            get {
                return ResourceManager.GetString("LengthCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset + count exceeds buffer.
        /// </summary>
        internal static string OffsetCountExceedsBuffer {
            get {
                return ResourceManager.GetString("OffsetCountExceedsBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offset negative.
        /// </summary>
        internal static string OffsetNegative {
            get {
                return ResourceManager.GetString("OffsetNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several calls to basestreams failed:.
        /// </summary>
        internal static string SeveralCallsToBasestreamsFailed {
            get {
                return ResourceManager.GetString("SeveralCallsToBasestreamsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream lenght limit exceeded!.
        /// </summary>
        internal static string StreamLenghtLimitExceeded {
            get {
                return ResourceManager.GetString("StreamLenghtLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The large stream must be readable, writable and seekable!.
        /// </summary>
        internal static string TheLargeStreamMustBeReadableWritableAndSeekable {
            get {
                return ResourceManager.GetString("TheLargeStreamMustBeReadableWritableAndSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The small stream must be readable, writable and seekable!.
        /// </summary>
        internal static string TheSmallStreamMustBeReadableWritableAndSeekable {
            get {
                return ResourceManager.GetString("TheSmallStreamMustBeReadableWritableAndSeekable", resourceCulture);
            }
        }
    }
}
